### ISSUE TITLE
Factory map floors issue

### ISSUE THREAD

**Issue by Shebuka** [TarkovTracker/tarkovdata#195]
In the Factory map, all floors seem to be the same top floor (with the second floor only getting some ladders) even if I can see parts of the lower floors and basement. Probably there are some floor groups naming issues.

**Comment by Shebuka** [comment]
This is still present... Now the most probable cause is that the floor has a space in it and when the `d3 selector` expands  the var in `select(`#${floor}`)`it becomes `.select(#First Floor)` without quotation around floor name

https://github.com/TarkovTracker/TarkovTracker/blob/d116ddddef61060d9a9f83fc902296a148efe6d2/src/components/TarkovMap.vue#L172

**Comment by austinhodak** [comment]
Resolved in #303
