### ISSUE TITLE
Schema change for locations on quests

### ISSUE THREAD

**Issue by SimplyAName** [TarkovTracker/tarkovdata#210]
I was planning on updating the "Punisher - Part 6" quest as it can no longer be done on Factory but see no way of updating it to allow multiple maps or excluding a map as "location" only takes a string.

Was planning on adding an array of maps minus Factory e.g:
`
"location": [ "Customs", "Woods", ...]
`

Let me know your thoughts on the change and I'll get on adding it 😄

**Comment by austinhodak** [comment]
Unfortunately this wouldn't work the way you suggest as it breaks backwards compatibility. The location field would need to stay the same.

**Comment by SimplyAName** [comment]
Could add an extra field for excluded maps when "location" is set to any?

"exclude" could be an array to allow for future quests where multiple maps could be disabled

e.g:
`
"location":"any",
"exclude": ["Factory"],
...`

Should allow older systems to go off "location" as normal with new systems using the exclude field to get a more accurate list.

**Comment by austinhodak** [comment]
Closing as the Tarkov.dev API is now the recommended source of data.
