### ISSUE TITLE
Add locales to quests

### ISSUE THREAD

**Issue by thaddeus** [TarkovTracker/tarkovdata#22]
Add a 'locales' map to quest objects to support localization strings, to start all current titles should be inserted as the 'en' locale

**Comment by obj** [comment]
@thaddeus 
Something like that? I guess we shouldn't remove the original "title" for backward compatibility. Or?
If that, I can do it for RU and EN.

>        "title": "Debut",
>        "locales": {
>            "en": "Debut",
>            "ru": "Проба пера"
>        },

**Comment by thaddeus** [comment]
@obj Yeah, exactly that would be fantastic - thanks! I'd probably leave the title for now, and it can be removed in a second step once the Tracker and Tools are updated to use the locales.

**Comment by thaddeus** [comment]
Resolved by #98
