### ISSUE TITLE
Mix of string types in quests.json

### ISSUE THREAD

**Issue by stphn** [TarkovTracker/tarkovdata#251]
in [quests.json](https://github.com/TarkovTracker/tarkovdata/blob/master/quests.json)

For most objectives of `type: key` the `target` is a string.
With some exception _(Spa Tour - Part 4 , Lend lease - Part 1 , ... )_ those quests have **multiple targets** --> **array of strings**.

### All quests:
``` javascript
"objectives": [
      {
        "type": "kill",
        "target": "Scavs", // one target
        "number": 5,
        "location": 1,
        "id": 0
      },
```

### Spa Tour - Part 4 :

``` javascript
"objectives": [
      {
        "type": "key",
        "target": ["5a13ef0686f7746e5a411744", "5a0ee34586f774023b6ee092"], // array of strings
        "number": 1,
        "location": 3,
        "id": 142
      },
```

---

### Possible solutions:

We should change `target` to `targets`**(plural)** with all targets inside an array.

It would become this
```javascript
"targets": ["Scavs"],
"targets": ["5a13ef0686f7746e5a411744", "5a0ee34586f774023b6ee092"],
```

Exactly the same has been done for `with` 

`"with": ["UNTAR helmet", "MF-UNTAR armor vest", "Colt M4A1"],`

This will approve the consistency of types and data structure.

**Comment by austinhodak** [comment]
Closing as the Tarkov.dev API is now the recommended source of data.
