### ISSUE TITLE
Replacing the "with" key in quests.json for another key name

### ISSUE THREAD

**Issue by stphn** [TarkovTracker/tarkovdata#252]
As mentioned [in this discussion](https://github.com/TarkovTracker/tarkovdata/discussions/249)
The `with` key is a reserved word and reserved word cannot be used as a shorthand property (React etc..).
Maybe replacing it with a name like `using` could solve some issues.

Meanwhile for TypeScript users you could try the following:
``` typescript
export const Objective = ({
    type,
    target,
    tool,
    with: using, // replacement
}: QuestObjective)
```

**Comment by austinhodak** [comment]
Closing as the Tarkov.dev API is now the recommended source of data.
