### ISSUE TITLE
Typo issue in quest "bullshit"

### ISSUE THREAD

**Issue by stphn** [TarkovTracker/tarkovdata#253]
### Do not kill any scavs from quest accept to quest complete

should be something like:

### Do not kill any scavs until the quest is completed

in [quests.json](https://github.com/TarkovTracker/tarkovdata/blob/master/quests.json) `line 2618`

```
{
        "type": "warning",
        "target": "Do not kill any scavs from quest accept to quest complete",
        "number": 1,
        "location": 1,
        "id": 110
      },
``

**Comment by austinhodak** [comment]
Fixed in #255
