### ISSUE TITLE
hard-coded values in quest "Sales Night" quests.json

### ISSUE THREAD

**Issue by stphn** [TarkovTracker/tarkovdata#254]
Issue: `number` and  `location` are hard-coded in the `target`

source [quests.json](https://github.com/TarkovTracker/tarkovdata/blob/master/quests.json): 

``` typescript
"objectives": [
      {
        "type": "warning",
        "target": "\"Survive\" Interchange 7 times (they do not have to be consecutive)",
        "number": 7,
        "location": 4,
        "id": 373
      }
    ],
```

Because `number` and  `location` are hard-coded in the `target` the text in fact should be

`"target": "Survive and extract (it does not have to be consecutive)",`

and then use it as follow:

```javascript
{target} + {number} + "times on" + {location} // or {`${target} ${number} times on ${location}`}

// Survive and extract (it does not have to be consecutive) 7 times on interchange
``` 

further thoughts:
(it does not have to be consecutive) == (could be done sequentially)

**Comment by austinhodak** [comment]
No longer an issue in the latest version.
