### ISSUE TITLE
incorrect caliber name

### ISSUE THREAD

**Issue by NooBiToo** [TarkovTracker/tarkovdata#261]
example
```
"5a608bf24f39f98ffc77720e": {
    "id": "5a608bf24f39f98ffc77720e",
    "name": "7.62x51mm M62 Tracer", ---> "M62 Tracer" or "M62" becouse we have property tracer: true
    "shortName": "M62",
    "weight": 0.024,
    "caliber": "Caliber762x51", ---> "Caliber 7.62x51" or "7.62x51" becouse property name = caliber
    "stackMaxSize": 40,
    "tracer": true,
    "tracerColor": "green",
    "ammoType": "bullet",
    "projectileCount": 1,
    "ballistics": {
      "damage": 79,
      "armorDamage": 75,
      "fragmentationChance": 0.14,
      "ricochetChance": 0.38,
      "penetrationChance": 0.67,
      "penetrationPower": 44,
      "accuracy": -6,
      "recoil": -5,
      "initialSpeed": 816
    }
  },
  ```

**Comment by Razzmatazzz** [comment]
I would recommend using the [Tarkov.dev API](https://tarkov.dev/api/) to get ammo information. It's updated almost in real-time via data provided by Tarkov Changes. This ammo json file is likely to become deprecated and no longer maintained.

**Comment by thaddeus** [comment]
> > I would recommend using the [Tarkov.dev API](https://tarkov.dev/api/) to get ammo information. It's updated almost in real-time via data provided by Tarkov Changes. This ammo json file is likely to become deprecated and no longer maintained.
> 
> last update 9 days ago

That is the date of a literal change, not that the API's data is outdated. There have been no ammo property changes since the wipe.
