### ISSUE TITLE
Missing Quest *Broadcast*

### ISSUE THREAD

**Issue by PoodyCZ** [TarkovTracker/tarkovdata#263]
https://escapefromtarkov.fandom.com/wiki/Broadcast

**Comment by PeterNilssonDev** [comment]
As a comment to this, on the wiki https://escapefromtarkov.fandom.com/wiki/Broadcast it says it requires signal part 2. I haven't even done signal part 1 and have unlocked this quest.

**Comment by r-gruber** [comment]
Pull request #268 has added "Broadcast" as well as "Top Secret"

**Comment by austinhodak** [comment]
Added in #268
