### ISSUE TITLE
Add missing quests

### ISSUE THREAD

**Issue by kokarn** [TarkovTracker/tarkovdata#32]
As reported by @DimaVartanian over at Discord, all the optional quests are missing from quests.json

https://escapefromtarkov.fandom.com/wiki/No_offence
https://escapefromtarkov.fandom.com/wiki/Trust_regain
https://escapefromtarkov.fandom.com/wiki/Hippocratic_Vow
https://escapefromtarkov.fandom.com/wiki/Loyalty_buyout

**Comment by thaddeus** [comment]
Thanks for making an issue for this! Been meaning to get to these - I didn't add them initially as I didn't support optional quest chains. I added sub-arrays within quest requires to allow 'one-of' requirements, as well as the alternatives array to indicate quests which are 'failed' when completing a quest. So I can get back to these once I finish the live team tracking.

**Comment by kokarn** [comment]
I figure it's nice to keep issues of what's missing as the discussion came up if this data was outdated because it was missing quests :D
