### ISSUE TITLE
Add missing gunsmith quest unlocks

### ISSUE THREAD

**Issue by kokarn** [TarkovTracker/tarkovdata#42]
Checked, and seems the unlocks for at least gunsmith pt 10, gunsmith pt 12 & gunsmith pt 13 are missing

**Comment by Razzmatazzz** [comment]
A Shooter Born in Heaven is also missing the Magazine Case unlock.

**Comment by thaddeus** [comment]
Sorry, yeah, unlocks are a bit of a mess from where I started them. Another thing I was thinking about is I don't know how unlocks should be better encapsulated. For example, sometimes you're unlocking the one and only trade for an item, other times you're unlocking a secondary trade or barter I believe. It would (probably) be valuable to keep track of what specific trade you're unlocking, but I don't know how to detail it, maybe either of you have an idea.

**Comment by Razzmatazzz** [comment]
The "variant" unlocks are tricky. It's also an issue with Scrap Metal unlocking the MP5 SD variant from Peacekeeper.

[Something like this](https://github.com/Razzmatazzz/tarkovdata/blob/master/trader_weapon_variants.json) might get us part of the way there. It currently includes extra fields to make it easier to see at a glance what's going on. 

The itemids are just internal DB ids from my website and I don't think we'd want to use those going forward. One option would be to use the ID from the weapon's receiver as the id for the overall preset. But that's not ideal as you can't really tell the preset apart from a stock version. In the case of presets that are unlocked via a quest, we could make combined ids using a system like "questid-baseweaponid". For weapons that just unlock at a particular trader level, we could use "traderid-requiredtraderlevel-baseweaponid". But even that's an imperfect solution as [some quests unlock multiple variants of the same weapon](https://escapefromtarkov.fandom.com/wiki/Hunting_trip).

**Comment by Razzmatazzz** [comment]
I think I've solved the issue of being able to refer to specific weapon variant unlocks with the changes in my latest pull request #46 .
