### ISSUE TITLE
Quest objective keys

### ISSUE THREAD

**Issue by Razzmatazzz** [TarkovTracker/tarkovdata#44]
Some quests, [for example Lend Lease Part 1](https://github.com/TarkovTracker/tarkovdata/blob/13d20fb695f58cd6427123df92b32eeb896cfbc2/quests.json#L1894-L1970), have key objectives that allow for multiple keys to be used interchangeably such as "East wing room 306 OR 308 key". In my last pull request, I left these instances as strings because this seems like something that should be a collective discussion and decision.

Does it break anything to change the "target" value from a string to an array in instances where items are interchangeable like this? That's what makes most sense to me, but I didn't want to unilaterally make that kind of structural change.

**Comment by thaddeus** [comment]
That sounds entirely reasonable to me, and a good solution to an obvious problem. I'm already substituting arrays in the required quests field for one-of selections, so it would make sense to keep doing that from my perspective.

**Comment by Razzmatazzz** [comment]
This is done in the pull request I just submitted.
