### ISSUE TITLE
Hideout items requirements

### ISSUE THREAD

**Issue by ferris1988** [TarkovTracker/tarkovdata#49]
Stash level 4 needs actually:

200.000 Euros
10 Bolts
10 Screws
5 shustrilo
2 ratchet

Solar power also needs 75.000 euros not 50.000.
![2021-05-26 14_21_30-EscapeFromTarkov](https://user-images.githubusercontent.com/7745509/119658734-c7cf7600-be2d-11eb-89d4-e132fabb4070.jpg)
![2021-05-26 14_21_44-EscapeFromTarkov](https://user-images.githubusercontent.com/7745509/119658737-c8680c80-be2d-11eb-979c-810b55b6444b.jpg)

**Comment by kokarn** [comment]
Thanks! Fixed :)
