### ISSUE TITLE
Add trader loyalty requirements to hideout modules

### ISSUE THREAD

**Issue by thaddeus** [TarkovTracker/tarkovdata#64]
Add the trader loyalty level requirements to appropriate hideout modules

**Comment by Ygnas** [comment]
What kind of scheme would you expect there? 
`                {
                    "type": "trader",
                    "name": "Skier",
                    "quantity": 3,
                    "id": "2"
                }`
Not sure what would you expect in name and id. Now id is his Skier id from traders.

**Comment by thaddeus** [comment]
Yeah, I think you have a good schema there. Just to clarify on the name/ID -
`{ "type": "trader", "name": "2", "quantity": 3, "id": 275 }` would be how we want to deal with IDs. 
The `id` field is a unique ID to all of the other hideout requirements. The `name` field should really be renamed to `target` as it shouldn't really be a name any more, but just a reference to what you need. In this case the `name` field would be the ID of skier in traders.

**Comment by thaddeus** [comment]
Resolved by #79 - thanks @Ygnas !
