### ISSUE TITLE
Requirement missing from Illumination level 3

### ISSUE THREAD

**Issue by DimaVartanian** [TarkovTracker/tarkovdata#69]
12 energy saving lamps is also required in addition to the capacitors and wires. I would have submitted a PR but I'm not sure what the number scheme is for the extra "id" attached to each requirement. Are you just incrementing by 1 for everything you add or is there something else?

**Comment by thaddeus** [comment]
Yeah, ids are just an incremental integer. Used to reference unique objectives/requirements with tracking tools. The CLI tool should give you a safe hideout objective ID to use (if you have node installed). You can do `node cli.js new-hideout-objective-id` to get a new ID. Currently it would be `274`
