### ISSUE TITLE
Add `stationId` to hideout modules

### ISSUE THREAD

**Issue by thaddeus** [TarkovTracker/tarkovdata#7]
Add a `stationId` property to hideout modules which is unique per module station (generator, workbench, bitcoin farm, etc) in addition to the unique ID per level of each station. This would make displaying unique stations easier in almost all situations.

**Comment by Monksman45** [comment]
You already have an id which is unique to all modules, can you give me an example? I could probably take a look.

**Comment by thaddeus** [comment]
What I'm thinking of is to get away from using `Module` as the identifier for a station. I'm thinking about this as a way to be as language agnostic as possible for possible use in tools with translations (something I'm hoping to start working on the near term with Tarkov Tracker). I would probably refactor hideout.json to be something more like:
```
stations: {
	0: {
		some_other_metadata_about_generator_that_isnt_level_specific,
		maybe_wiki_link_to_hideout#generator,
		locales: {
			'en': 'Generator',
			'de': 'Générateur',
			...
		}
	},
	1: {
		...
		locales: {
			'en': 'Workbench',
			...
		}
		...
	},
	...
},
modules: {
	...all_the_current_hideout.json_data_with_the_relevant_station_ids_added
}
```
If you're interested in taking a stab at it, that would be awesome, if not, no worries! Obviously the translation data outside of 'en' could be omitted for now, unless of course you know any of the other languages Tarkov is translated into or can get the translations with ease. I plan on asking people if they would like to help in that regards when I start working on it with the tracker.

**Comment by Monksman45** [comment]
Ok, I see what you're saying. Basically you want to decouple some of the basic information into it's own object. Yeah, I can give it a shot!

**Comment by thaddeus** [comment]
Exactly - with the current setup any common information would need to be duplicated, also unique stations are explicitly defined, but rather implicitly via matching module names, so splitting that out would be good practice IMO. Thanks!

**Comment by patrickderitter** [comment]
Updated some of the work done by @Monksman45 in #9, noticed the numbering was off. See #10.

**Comment by thaddeus** [comment]
I think this is pretty well accomplished, thank you very much @Monksman45 and @patrickderitter !
