### ISSUE TITLE
Add crafting recipes to hideout modules

### ISSUE THREAD

**Issue by thaddeus** [TarkovTracker/tarkovdata#8]
Add hideout station crafts to the hideout.json file - for Tarkov Tracker this will enable showing tips for quest requirements which can be crafted instead of found in game.

Something like
```
crafts: [{craftId: 4, produce: {item: "Bandage" quantity: 6}, ingredients: [{item: "Fleece cloth", quantity: 1}]}]
```

**Comment by kokarn** [comment]
Hey! Love the work with Tarkov tracker! 
You can get all the above data from the tarkov-tools API

http://tarkov-tools.com/___graphql

```
{
                crafts {
                  rewardItems {
                    item {
                      id
                      name
                    }
                    count
                  }
                  requiredItems {
                    item {
                      id
                      name
                    }
                    count
                  }
                  source
                  time
                }
            }
```

**Comment by thaddeus** [comment]
> Hey! Love the work with Tarkov tracker!
> You can get all the above data from the tarkov-tools API
> 
> http://tarkov-tools.com/___graphql
> 
> ```
> {
>                 crafts {
>                   rewardItems {
>                     item {
>                       id
>                       name
>                     }
>                     count
>                   }
>                   requiredItems {
>                     item {
>                       id
>                       name
>                     }
>                     count
>                   }
>                   source
>                   time
>                 }
>             }
> ```

Thanks! Pleasure to meet you - tarkov-tools has been super helpful for me as a player for a good while now - thank you!

The data looks awesome, pretty much exactly what I'm looking for! Thanks!

**Comment by kokarn** [comment]
Thx for the kind words! That's exactly why I'm building it, to help players such as us :)

Glad the data looks good for you! It's the same I use, so should hopefully be kept correct :D
